export const cartProductsTypes = {
    ADD_PRODUCT_TO_CART : "ADD_PRODUCT_TO_CART",
    REMOVE_ONE_PRODUCT_FROM_CART : "REMOVE_ONE_PRODUCT_FROM_CART",
    REMOVE_PRODUCT_FROM_CART : "REMOVE_PRODUCT_FROM_CART",
    UPDATE_SUM : "UPDATE_SUM",
    EMPTY_SHOPPING_CART : "EMPTY_SHOPPING_CART",
    OPEN_CART_FORM : "OPEN_CART_FORM",
    CLOSE_CART_FORM : "CLOSE_CART_FORM",
    SET_ORDER_NUMBER : "SET_ORDER_NUMBER"
}

export const favoritesProductsTypes = {
    ADD_PRODUCT_TO_FAVORITES : "ADD_PRODUCT_TO_FAVORITES",
    REMOVE_PRODUCT_FROM_FAVORITES : "REMOVE_PRODUCT_FROM_FAVORITES",
}

export const modalTypes = {
    OPEN_ADD_PRODUCT_MODAL : "OPEN_ADD_PRODUCT_MODAL",
    CLOSE_ALL_MODALS : "CLOSE_ALL_MODALS",
    OPEN_DEL_PRODUCT_MODAL : "OPEN_DEL_PRODUCT_MODAL",
    OPEN_DEL_FAVORITE_MODAL : "OPEN_DEL_FAVORITE_MODAL",
    OPEN_PURCHASE_MODAL : "OPEN_PURCHASE_MODAL"
}

export const productTypes = {
    FETCH_DATA_SUCCESS : "FETCH_DATA_SUCCESS",
}